---
- name: Get latest release of a borgbackup repository
  delegate_to: localhost
  run_once: True
  uri:
    url: https://api.github.com/repos/borgbackup/borg/releases/latest
  register: borg_latest

- name: install borg backup
  get_url:
    dest: "/usr/local/bin/borg"
    owner: "{{ borgbackup_owner }}"
    group: "{{ borgbackup_group }}"
    mode: "0755"
    url: 'https://github.com/borgbackup/borg/releases/download/{{ borg_latest.json.tag_name }}/borg-linux64'
    force: yes
  when: ansible_os_family == "Debian"

- name: install borg support packages
  apt: 
    name: '{{ borgbackup_packages }}'
    force_apt_get: yes
  when: ansible_os_family is defined and ansible_os_family == "Debian"

- name: install borg
  apk:
    name: 'borgbackup'
  when: ansible_distribution == "Alpine"

- name: install borg support packages
  apk:
    name: '{{ borgbackup_packages }}'
  when: ansible_distribution == "Alpine"
