---
- name: install borg backup
  get_url:
    dest: "/usr/local/bin/borg"
    owner: "{{ borgbackup_owner }}"
    group: "{{ borgbackup_group }}"
    mode: "0755"
    url: "{{ borgbackup_download_url }}"
    force: yes

- name: install borg support packages
  apt: 
    pkg: '{{ item }}'
  with_items: '{{ borgbackup_packages }}'
